---
kind: pipeline
name: test
type: docker

steps:
  - name: install
    image: composer
    commands:
      - composer install

  - name: test
    image: php:cli-alpine
    commands:
      - ./vendor/bin/phpunit --configuration phpunit.xml
